### 1.2 login for new register
POST {{url}}/login
Content-Type: application/json;charset=UTF-8

{
  "username": "admin",
  "password": "admin"
}

### 1.2 login for exist client
POST {{url}}/login
Content-Type: application/json;charset=UTF-8

{
  "username": "root",
  "password": "root"
}

