server:
  port: 8070
spring:
  h2.console.enabled: true

  # h2
  datasource.data: classpath:/sql/init-data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
    hibernate:
      ddl-auto: create-drop
      naming:
        # use camel case in database
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


